"""
AlphaHunt — AI "current read" thesis generator.

Produces a tight 2–3 sentence, plain-English summary of a stock's CURRENT
situation, generated by Claude (Haiku) grounded ONLY on the ticker's own live
data (price, Alpha score, signals, margins, growth, valuation, recent news
headlines). No web search — fast and cheap. No buy/sell advice, no targets.

Returns the summary string; caller caches it.
"""
from __future__ import annotations

import json
import logging
import os

import httpx

logger = logging.getLogger(__name__)

_KEY     = os.environ.get("ANTHROPIC_API_KEY", "").strip()
_MODEL   = (os.environ.get("ANTHROPIC_MODEL") or "claude-haiku-4-5-20251001").strip()
_TIMEOUT = float(os.environ.get("THESIS_TIMEOUT", "20"))


def available() -> bool:
    return bool(_KEY)


def _ctx(t: dict) -> dict:
    """Compact, current ground-truth context for the model."""
    news = [
        (a.get("headline") or a.get("title"))
        for a in (t.get("news") or [])[:5]
        if (a.get("headline") or a.get("title"))
    ]
    keys = [
        "ticker", "name", "sector", "sub_sector", "price", "change_pct",
        "smart_score", "pop_score", "grade", "signals", "caution_reasons",
        "revenue_growth_yoy", "gross_margin", "profit_margin", "eps_beat_streak",
        "days_to_earnings", "pe_ratio", "target_upside_pct", "rsi_14",
        "momentum_1m", "momentum_3m", "dist_52w_high",
    ]
    ctx = {k: t.get(k) for k in keys if t.get(k) is not None}
    if news:
        ctx["recent_news"] = news
    return ctx


_PROMPT = (
    "You are an equity-research assistant. Using ONLY the JSON data below, write a "
    "concise plain-English 'current read' on this stock for a long-term investor: "
    "2–3 sentences, ~55 words max. Lead with what stands out right now (momentum, "
    "growth, valuation, ownership, or an upcoming catalyst), then note the main "
    "caveat or risk. No buy/sell/hold advice, no price targets, no invented numbers, "
    "no preamble or markdown. Output only the summary sentences.\n\nDATA:\n"
)


async def generate_thesis(ticker: str, t: dict | None) -> str:
    if not available():
        raise RuntimeError("ANTHROPIC_API_KEY not configured")
    t = t or {"ticker": ticker.upper()}
    body = {
        "model": _MODEL,
        "max_tokens": 240,
        "messages": [{"role": "user", "content": _PROMPT + json.dumps(_ctx(t), default=str)}],
    }
    async with httpx.AsyncClient(timeout=_TIMEOUT) as c:
        r = await c.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": _KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json=body,
        )
        if r.status_code >= 400:
            logger.error(f"thesis_gen {ticker} → {r.status_code}: {r.text[:200]}")
        r.raise_for_status()
        data = r.json()
    parts = [b.get("text", "") for b in data.get("content", []) if b.get("type") == "text"]
    return "".join(parts).strip()
